language: python
python:
  - "2.7"

before_install:
  - nvm install 4.6
  - nvm use 4.6

install:
  - pip install -r requirements.txt
  - npm install

before_script:
  - pip freeze

script:
  - py.test tests